version: '3'
services:
  drone_server:
    build:
      dockerfile: .docker/server/Dockerfile
      context: .
    container_name: drone_server
    env_file:
      - .env
    volumes:
      - "./data:/data"
      - "./logs:/logs"
      - ".uploads:/uploads"
    ports:
      - 8484:8484
  drone_log_register:
    build:
      dockerfile: .docker/log_register/Dockerfile
      context: .
    container_name: drone_log_register
    env_file:
      - .env
    volumes:
      - "./data:/data"
      - "./logs:/logs"
      - "./uploads:/uploads"
  tools:
    build:
      dockerfile: .docker/tools/Dockerfile
      context: .
    container_name: tools
